"""Native Codex plugin support: codex_plugins param -> [plugins.*] entries
in the generated config.toml, managed-section markers, preservation of
content written outside the markers (codex plugin state, user edits).

No Docker, no codex binary: _codex_setup_mcp_config is exercised directly
against tmp_path with the relay lookup and token mint stubbed.
"""

import os

import pytest

from core.llm_providers.codex_session import CodexSessionMixin


class _Host(CodexSessionMixin):
    """Minimal mixin host: only what _codex_setup_mcp_config touches."""

    def __init__(self, config=None):
        self.config = config or {}

    @classmethod
    def _get_tool_relay_info(cls):
        return "ws://localhost:1234/ws/tools/x", "relay-token"


@pytest.fixture(autouse=True)
def _stub_token(monkeypatch):
    from core import internal_auth
    monkeypatch.setattr(internal_auth, "mint_token", lambda: "tok-test")


def _write_config(tmp_path, config=None):
    host = _Host(config=config)
    path, token = host._codex_setup_mcp_config(
        str(tmp_path), user_id="u1", conversation_id="c1", agent_name="a1")
    assert token == "tok-test"
    with open(path, "r", encoding="utf-8") as f:
        return path, f.read()


class TestPluginSpecs:
    def test_empty_and_missing(self):
        assert _Host({})._codex_plugin_specs() == []
        assert _Host({"codex_plugins": ""})._codex_plugin_specs() == []
        assert _Host({"codex_plugins": " , ,"})._codex_plugin_specs() == []

    def test_default_marketplace_and_qualified(self):
        specs = _Host({"codex_plugins":
                       "github, linear@acme-market ,gmail"})._codex_plugin_specs()
        assert specs == ["github@openai-curated", "linear@acme-market",
                         "gmail@openai-curated"]


class TestConfigToml:
    def test_no_plugins_no_plugin_tables(self, tmp_path):
        _, content = _write_config(tmp_path)
        assert "[plugins." not in content
        assert "[mcp_servers.pawflow]" in content
        assert content.startswith(CodexSessionMixin._CODEX_MANAGED_BEGIN)
        assert CodexSessionMixin._CODEX_MANAGED_END in content

    def test_plugin_entries_emitted(self, tmp_path):
        _, content = _write_config(
            tmp_path, {"codex_plugins": "github,linear"})
        assert '[plugins."github@openai-curated"]\nenabled = true' in content
        assert '[plugins."linear@openai-curated"]\nenabled = true' in content
        # Plugins live INSIDE the managed section (regenerated per session).
        managed_end = content.index(CodexSessionMixin._CODEX_MANAGED_END)
        assert content.index('[plugins."github@openai-curated"]') < managed_end

    def test_managed_keys_stay_root_scoped(self, tmp_path):
        """Top-level keys must precede any table header in the output."""
        _, content = _write_config(tmp_path, {"codex_plugins": "github"})
        first_table = content.index("[")
        assert content.index("model_auto_compact_token_limit") < first_table
        assert content.index("suppress_unstable_features_warning") < first_table

    def test_legacy_file_without_markers_is_replaced(self, tmp_path):
        codex_home = tmp_path / ".codex"
        codex_home.mkdir()
        (codex_home / "config.toml").write_text(
            "# Auto-generated by PawFlow — do not edit.\nold = true\n",
            encoding="utf-8")
        _, content = _write_config(tmp_path)
        assert "old = true" not in content

    def test_outside_marker_content_preserved_across_rewrites(self, tmp_path):
        path, _ = _write_config(tmp_path, {"codex_plugins": "github"})
        # Simulate `codex plugin install` appending its own state.
        with open(path, "a", encoding="utf-8") as f:
            f.write('\n[plugins."canva@openai-curated"]\nenabled = true\n')
        _, content = _write_config(tmp_path, {"codex_plugins": "github"})
        assert '[plugins."canva@openai-curated"]' in content
        assert '[plugins."github@openai-curated"]' in content
        # Preserved content sits AFTER the managed section.
        assert (content.index('[plugins."canva@openai-curated"]')
                > content.index(CodexSessionMixin._CODEX_MANAGED_END))

    def test_rewrite_is_stable_no_duplicate_managed_sections(self, tmp_path):
        _write_config(tmp_path, {"codex_plugins": "github"})
        _write_config(tmp_path, {"codex_plugins": "github"})
        _, content = _write_config(tmp_path, {"codex_plugins": "github"})
        assert content.count(CodexSessionMixin._CODEX_MANAGED_BEGIN) == 1
        assert content.count(CodexSessionMixin._CODEX_MANAGED_END) == 1
        assert content.count('[plugins."github@openai-curated"]') == 1

    def test_plugin_removal_on_config_change(self, tmp_path):
        _write_config(tmp_path, {"codex_plugins": "github"})
        _, content = _write_config(tmp_path, {"codex_plugins": ""})
        assert "[plugins." not in content

    def test_file_permissions(self, tmp_path):
        path, _ = _write_config(tmp_path)
        assert oct(os.stat(path).st_mode & 0o777) == "0o600"


class TestServiceSchema:
    def test_codex_plugins_param_declared_and_scoped(self):
        from services.llm_connection import LLMConnectionService
        schema = LLMConnectionService.get_parameter_schema(
            LLMConnectionService.__new__(LLMConnectionService))
        assert "codex_plugins" in schema
        rules = LLMConnectionService.get_parameter_rules(
            LLMConnectionService.__new__(LLMConnectionService))
        visible_for = [r["when"]["provider"] for r in rules
                       if r["set"].get("codex_plugins", {}).get("visible")]
        assert visible_for == [["codex-app-server"]]
