"""Agent-facing handlers for extra media capabilities.

Each handler is provider-agnostic: it calls a resolver `() -> (service,
error_msg)` wired by `AgentToolConfigMixin` at request time, then
delegates to the service's public method. File storage is routed
through `core.storage_resolver.StorageResolver`, same pattern as
`ImageGenerationHandler` / `VideoGenerationHandler`.
"""

import functools
import logging
import os
from typing import Any, Dict

from core.tool_handler import ToolHandler

logger = logging.getLogger(__name__)

_SERVICE_ARG_NAMES = (
    "service", "image_service", "video_service", "audio_service", "voice_service")
_INTERNAL_TTS_ARG_NAMES = ("_tts_storage_ttl", "transient", "transient_ttl", "ttl")


def _resolve_filestore_url(url: str, base_url: str, service=None) -> str:
    """Convert fs://filestore/<id>/<name> to HTTP unless service reads it locally."""
    if not url or not url.startswith("fs://filestore/"):
        return url
    if service is not None and getattr(service, "ACCEPTS_FILESTORE_URLS", False):
        return url
    rest = url[len("fs://filestore/"):]
    fid = rest.split("/", 1)[0]
    if not fid:
        return url
    return f"{base_url.rstrip('/')}/files/{fid}"


def _write_result(user_id: str, conversation_id: str,
                   destination: str, filename: str,
                   payload: bytes, content_type: str) -> Dict[str, Any]:
    """Persist the generated bytes via StorageResolver, return its dict."""
    from core.storage_resolver import StorageResolver
    resolver = StorageResolver(
        user_id=user_id, conversation_id=conversation_id or "")
    return resolver.write(destination, filename, payload, content_type)


def _write_result_file(user_id: str, conversation_id: str,
                       destination: str, filename: str,
                       source_path: str, content_type: str) -> Dict[str, Any]:
    """Persist a generated local file via StorageResolver."""
    from core.storage_resolver import StorageResolver
    resolver = StorageResolver(
        user_id=user_id, conversation_id=conversation_id or "")
    return resolver.write_file(destination, filename, source_path, content_type)


def _provider_identity(svc) -> str:
    runtime = getattr(svc, "config", {}).get("package_runtime", {}) \
        if isinstance(getattr(svc, "config", None), dict) else {}
    if runtime:
        package = str(runtime.get("package") or "")
        object_id = str(runtime.get("object_id") or "")
        if package and object_id:
            return f"pfp:{package}/{object_id}"
    return getattr(svc, "TYPE", svc.__class__.__name__)


def _provider_version(svc) -> str:
    config = getattr(svc, "config", {})
    runtime = config.get("package_runtime", {}) if isinstance(config, dict) else {}
    if runtime:
        installed = config.get("installed_from", {}) if isinstance(config, dict) else {}
        version = str(runtime.get("version") or "")
        digest = str(installed.get("hash") or "")
        return f"{version}:{digest}" if digest else version
    return getattr(svc, "VERSION", "0")


def _voice_id_value(value) -> str:
    """Normalize provider voice-id results to the provider-opaque string."""
    if isinstance(value, dict):
        return str(value.get("voice_id") or value.get("id") or "")
    return str(value or "")


class _CapabilityHandlerBase(ToolHandler):
    """Shared wiring for the capability handlers (3D/upscale/try-on/...)."""

    _base_url: str = "http://localhost:9090"
    _service_resolver = None  # () -> (service, error_msg)
    _user_id: str = ""
    _conversation_id: str = ""
    _agent_name: str = ""
    _share = None  # active TemporaryPublicRefs for the current execute() call

    def __init_subclass__(cls, **kwargs):
        """Wrap each concrete handler's execute() in a temporary-share scope.

        Every capability handler routes its reference inputs through
        ``_rewrite``; wrapping ``execute`` here means each call shares the
        referenced FileStore files as public, gateway-key URLs for the
        duration of the call and revokes them afterwards — success or
        failure — without per-handler boilerplate.
        """
        super().__init_subclass__(**kwargs)
        raw_execute = cls.__dict__.get("execute")
        if raw_execute is None:
            return  # inherits an already-wrapped execute

        @functools.wraps(raw_execute)
        def _execute_with_share(self, arguments, _raw=raw_execute):
            from core.media_share import TemporaryPublicRefs
            self._share = TemporaryPublicRefs(self._base_url, self._user_id)
            try:
                return _raw(self, arguments)
            finally:
                self._share.restore()
                self._share = None

        cls.execute = _execute_with_share

    def set_base_url(self, base_url: str):
        self._base_url = base_url.rstrip("/")

    def set_user_id(self, user_id: str):
        self._user_id = user_id

    def set_conversation_id(self, conversation_id: str):
        self._conversation_id = conversation_id

    def set_agent_name(self, agent_name: str):
        self._agent_name = agent_name

    def set_service_resolver(self, resolver):
        self._service_resolver = resolver

    def _get_service(self, arguments: Dict[str, Any] = None):
        arguments = arguments or {}
        service_name = (arguments.get("service")
                        or arguments.get("image_service")
                        or arguments.get("video_service")
                        or arguments.get("audio_service")
                        or arguments.get("voice_service")
                        or "")
        if service_name:
            try:
                from core.service_registry import ServiceRegistry
                svc = ServiceRegistry.get_instance().resolve(
                    service_name,
                    user_id=self._user_id,
                    conv_id=self._conversation_id,
                )
            except Exception as exc:
                return None, f"media service '{service_name}' failed to resolve: {exc}"
            if not svc:
                return None, f"media service '{service_name}' not found or not connected"
            if hasattr(svc, "set_runtime_context"):
                svc.set_runtime_context(
                    user_id=self._user_id,
                    conversation_id=self._conversation_id,
                    agent_name=self._agent_name,
                )
            if hasattr(svc, "set_callback_base_url"):
                svc.set_callback_base_url(self._base_url)
            return svc, ""
        if not self._service_resolver:
            return None, "no service resolver configured"
        svc, err = self._service_resolver()
        if svc and hasattr(svc, "set_runtime_context"):
            svc.set_runtime_context(
                user_id=self._user_id,
                conversation_id=self._conversation_id,
                agent_name=self._agent_name,
            )
        if svc and hasattr(svc, "set_callback_base_url"):
            svc.set_callback_base_url(self._base_url)
        return svc, err

    def _rewrite(self, url: str, service=None) -> str:
        # Inside execute() the call runs within a temporary-share scope, so
        # FileStore refs become public gateway-key URLs that are revoked when
        # the call returns. Outside that scope, fall back to the legacy form.
        share = getattr(self, "_share", None)
        if share is not None:
            return share.public_url(url, service=service)
        return _resolve_filestore_url(url, self._base_url, service=service)

    def _persist(self, destination: str, filename: str, result: Dict[str, Any],
                 label: str) -> str:
        """Write the service result to storage + return a user-facing message."""
        ct = result.get("content_type", "application/octet-stream")
        payload = result.get("bytes") or result.get("image_bytes") \
            or result.get("video_bytes") or result.get("audio_bytes") or b""
        source_path = result.get("path") or result.get("image_path") \
            or result.get("video_path") or result.get("audio_path") or ""
        if source_path:
            try:
                write_result = _write_result_file(
                    self._user_id, self._conversation_id,
                    destination, filename, str(source_path), ct)
            finally:
                if result.get("_delete_media_path"):
                    try:
                        os.unlink(str(source_path))
                    except OSError:
                        pass
            if write_result.get("file_id"):
                url = f"fs://filestore/{write_result['file_id']}/{filename}"
                return f"{label}: {url}\nfile_id: {write_result['file_id']}"
            return (f"{label} saved to "
                    f"{write_result.get('destination', destination)}: "
                    f"{write_result.get('path', filename)}")
        if not payload:
            return f"Error: {label} returned no payload"
        write_result = _write_result(
            self._user_id, self._conversation_id,
            destination, filename, payload, ct)
        if write_result.get("file_id"):
            url = f"fs://filestore/{write_result['file_id']}/{filename}"
            return f"{label}: {url}\nfile_id: {write_result['file_id']}"
        return (f"{label} saved to "
                f"{write_result.get('destination', destination)}: "
                f"{write_result.get('path', filename)}")


# ── 3D ─────────────────────────────────────────────────────────────────


