const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pawflowRelay', {
  list: () => ipcRenderer.invoke('relay:list'),
  addServer: input => ipcRenderer.invoke('relay:add-server', input),
  deleteServer: name => ipcRenderer.invoke('relay:delete-server', name),
  loginServer: name => ipcRenderer.invoke('relay:login-server', name),
  savePhysical: input => ipcRenderer.invoke('relay:save-physical', input),
  deletePhysical: name => ipcRenderer.invoke('relay:delete-physical', name),
  start: name => ipcRenderer.invoke('relay:start', name),
  stop: name => ipcRenderer.invoke('relay:stop', name),
  forceCleanup: name => ipcRenderer.invoke('relay:force-cleanup', name),
  killInflight: name => ipcRenderer.invoke('relay:kill-inflight', name),
  restart: name => ipcRenderer.invoke('relay:restart', name),
  running: () => ipcRenderer.invoke('relay:running'),
  selectDirectory: currentPath => ipcRenderer.invoke('relay:select-directory', currentPath),
  listDockerImages: () => ipcRenderer.invoke('relay:docker-images'),
  relayImageCatalog: () => ipcRenderer.invoke('relay:image-catalog'),
  buildRelayImage: input => ipcRenderer.invoke('relay:build-image', input),
  downloadRelayImage: input => ipcRenderer.invoke('relay:download-image', input),
  keyStatus: () => ipcRenderer.invoke('relay:key-status'),
  keyExportPubkey: () => ipcRenderer.invoke('relay:key-export-pubkey'),
  keyInit: passphrase => ipcRenderer.invoke('relay:key-init', passphrase),
  keyRotate: passphrase => ipcRenderer.invoke('relay:key-rotate', passphrase),
  onLog: callback => ipcRenderer.on('relay-log', (_event, payload) => callback(payload)),
});
